termux-user-repository/tur

disabled-tur/openblas/build.sh, disabled-tur/python-scipy/build.sh, tur/python-numpy/build.sh
These packages are built with old NDK toolchain, and I think they will not be accepted by the main repo.
Test results are as following:
**Numpy Test Results**
| Architecture / RAM Size | Android Version | Result | Comment |
| :----: | :----: | :----: | :----: |
| AArch64 / 12G | 11.0 | 18 failed, 17619 passed, 342 skipped, 1302 deselected, 39 xfailed, 2 xpassed, 9 errors in 165.51s (0:02:45) | |
| ARM / 6G | 9.0 | 4 failed, 17071 passed, 1191 skipped, 1302 deselected, 39 xfailed, 2 xpassed, 19 warnings, 9 errors in 380.60s (0:06:20) | |
| X86-64 / 4G | 7.0 | 8 failed, 17721 passed, 1442 skipped, 1302 deselected, 36 xfailed, 5 xpassed, 4 warnings, 9 errors in 113.52s (0:01:53) | On a BlueStacks 5 VM |
| X86 / 4G | 7.0 | 3 failed, 17707 passed, 1450 skipped, 1302 deselected, 39 xfailed, 2 …
=> new package: python-numpy

tur/sqawk/build.sh
~~tcllib is the standard library of tcl.  Some module like `ftpd` use hardcoded path (we have busybox anyway).~~
sqawk is a maintained CLI utility depends on tcllib -- have to say that only [a few](https://github.com/search?q=language%3Atcl+stars%3A%3E50+pushed%3A%3E2020-01-01&ref=simplesearch) maintained project on GitHub still use tcl, too few to create a `termux_setup_tcl` for it.
=> new package: sqawk

tur/fakepkg/00-hardcoded-path.patch, tur/fakepkg/01-android-chdir-fsroot-eperm-gnutar-dieout-fix.patch, tur/fakepkg/build.sh
what: modern analogue of deprecated `bacman(8)` script, which is previously dist within pacman as a contrib script, https://gitlab.archlinux.org/pacman/pacman/-/commit/ae56a32273df8a36f4e84e0f37ce1f34e84f15a3
=> new package: fakepkg

tur/agg/build.sh
I forgot to specify the target architecture in `agg` build script, as a result all packages were built for `x86-64`.
=> package agg: fix compilation target architecture

tur/libraw/build.sh, tur/libspnav/build.sh, tur/libspnav/makefile.patch, tur/openimageio/build.sh, tur/openimageio/disable-neon.patch, tur/openimageio/prefix.patch, tur/openvdb/build.sh, tur/pybind11/build.sh
As Blender does not support cross-compiling, I decided to use Tur-on-device. In order to build Blender, I need these dependencies, as they would not be accepted in termux-packages.
=> add(tur): blender deps

tur/python-mitmproxy-wireguard/build.sh
=> bump(tur/python-mitmproxy-wireguard): 0.1.21

tur-on-device/perl-net-ssleay/build.sh
So that perl-net-ssleay installs to `$PREFIX/lib/perl5/5.36.1` where the other perl stuff currently resides.
=> perl-net-ssleay: bump after perl update

tur/ffmpeg5.1/build.sh, tur/ffmpeg5.1/enable-soname-version.patch, tur/ffmpeg5.1/libavutil-file_open.c.patch
FFmpeg 6.0 is in the Termux official repo:
https://github.com/termux/termux-packages/tree/master/packages/ffmpeg
but PyAV currently doesn't build against FFmpeg 6.0 version due to removal of several deprecated features, including the flags AV_CODEC_CAP_TRUNCATED, AV_CODEC_CAP_AUTO_THREADS, AV_CODEC_CAP_INTRA_ONLY, AV_CODEC_CAP_LOSSLESS, and AVFMT_FLAG_PRIV_OPT.
The problem is reported in PyAV: 
https://github.com/PyAV-Org/PyAV/issues/1106
I'm adding ffmpeg 5.1.2 package to successfully build PyAV against it.
Thanks
=> New package ffmpeg 5.1.2

tur/code-server/build.sh
=> code-server: bump to 4.17.0

tur-on-device/python-tokenizers/build.sh
=> python-tokenizers: bump to 0.15.1

tur/python-fitsio/build.sh
A dependency of astrometry.net, as mentioned in https://github.com/termux-user-repository/tur/issues/844. 
I can try building astrometry.net with `tur-on-device` only after this is pull request is accepted (`python-fitsio` cannot be built in `tur-on-device`, throwing [`x86_64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'`](https://github.com/knyipab/tur/actions/runs/8035672334/job/21948565280#step:7:5035)).
=> new package: python-fitsio

tur/astrometry.net-data-basic/build.sh, tur/astrometry.net-data-basic/copyright, tur/astrometry.net/0001-gsl-an-configure-cross-compile.patch, tur/astrometry.net/0002-solver-landroid-glob.patch, tur/astrometry.net/0003-ioutils-TMPDIR.patch, tur/astrometry.net/0004-bypass-netpbm-test.patch, tur/astrometry.net/build.sh
Few caveats:
* arm cannot cross compile for unknown reason and fails the configure test on CC ([this action log just FYI](https://github.com/knyipab/tur/actions/runs/8042104268)). I gave up fixing it and blacklisted this arch. 
* The most controversial patch is perhaps `tur/astrometry.net/0004-bypass-netpbm-test.patch`, needed becuz it does not run cross-compiled executable. With `netpbm` package installed and it does compile and links the libs, we can simply assume it to work. (Without netpbm on, `plot-constellations` in the test below will fail)
Tested working on my aarch64 device with a [Google Pixel Astrophoto from Google Blog](https://blog.research.google/2019/11/astrophotography-with-night-sight-on.html)
```
wget https://1.bp.blogspot.com/-RET3jzHjUdI/Xd2Z3zO_bVI/AAAAAAAAE-g/m9gTuElm …
```
=> astrometry.net and index files

tur/astrometry.net/0001-gsl-an-configure-cross-compile.patch, tur/astrometry.net/build.sh
The patch on command ./configure `--host` shouldn't be hard-coded.
=> astrometry.net: fix host arch

tur/skyseg-ncnn/build.sh
A cmake build of xiongzhu666/Sky-Segmentation-and-Post-processing. Because in the original repository, the binary source code has no build script, no release and neither that relative path works well for Termux, I created a repository dedicated for it. This package is actually one of the building block of a tool I plan to package on TUR. 
Test script (for record)
```bash
curl -o demo.jpg -L https://lh3.googleusercontent.com/pw/AP1GczNsgYY61QHlnYai--x-scRy_QJbkqGyASQN39lcL5ZD_AcMitUQqQ8mWy8Bf_FruvknK0_Pw77VqO84FtGU4z8OZMWP2qWAkRnqHUrZYESZiuFNKpCHEzXCpQ6fdeT1wbiJuCgtbcea_60ym7NAzwxN=w943-h1257-s-no-gm
skyseg-ncnn demo.jpg demo-sky.jpg
```
In the test, it works well even for night sky.
=> new package: skyseg-ncnn

tur-hacking/ettercap/CMakeLists.txt.patch, tur-hacking/ettercap/build.sh, tur-hacking/ettercap/cmake-Modules-EttercapLibCheck.cmake.patch, tur-hacking/ettercap/cmake-Modules-EttercapOSTest.cmake.patch, tur-hacking/ettercap/ettercap-0.8.3.1-libcurl-8.patch, tur-hacking/ettercap/include-ec_threads.h.patch, tur-hacking/ettercap/src-ec_threads.c.patch, tur-hacking/ettercap/src-ec_ui.c.patch
Ettercap could be considered a dual-use package and could perhaps be put in tur-hacking instead. Plese let me know if that is preferable.
=> ettercap: move from termux-packages/root-packages

tur/realesrgan-ncnn-vulkan/build.sh
Let me wait for the aarch64 build here and then test on my device (cuz the Github Actions in my repo does build aarch64 pkg). Will provide test result of this package in later comments. 
By the way, this git repo uses ssh in submodules (i.e. `git@github.com` in `.gitmodules`) which fails in submodules updates during build, so I override `termux_step_get_source()`. Adjust it if you may find more elegant workaround. 
Besides, on-device build might by necessary, because glslangValidator has to be caclled by shell, shown in (this build using ubuntu)[https://github.com/knyipab/tur/actions/runs/9098779611/job/25009778832]. Again, welcome workarond if you know.
=> new package: realesrgan-ncnn-vulkan

tur/leanify/build.sh
Requested in: 
- termux/termux-packages#20885
> [!NOTE]
> Checklist:
> - [x] Builds locally
> - [ ] Builds on CI
> - [x] Tested on device (Android 13, AArch64, Fairphone 5)
<h1><em></em></h1> 
@TPS, if you wouldn't mind I'd appreciate if you could check the package for correct functioning.
I just did a basic "does it print its help and version information" test.
Instructions below.
<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux-user-repository/tur/actions/runs/9987167934).
After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>
```bash …
```
=> addpkg(tur/leanify): 0.4.3+20231217

tur/zerotier-one/0001-mask-setattr.patch, tur/zerotier-one/0002-rust-target-os.patch, tur/zerotier-one/0003-osutils-termux-prefix.patch, tur/zerotier-one/0004-makefile-arm-workaround.patch, tur/zerotier-one/0005-makefile-cargo-target-name.patch, tur/zerotier-one/0006-makefile-clang-simulate-as.patch, tur/zerotier-one/0007-makefile-checkdep-destdir.patch, tur/zerotier-one/0008-makefile-install-add-selftest.patch, tur/zerotier-one/build.sh
- port for rust build
- use static build on arm to satisfy lld linking with plain asm
- install zerotier-selftest
- adjust config location for termux
zerotier-one needs to create network interface, so NET_* capabilities should be given.
currently zerotier seemed to use route table related to `ip route`, which is not useful under android. To use it conveniently future works like scripts for convert `ip route` to `ip rule` are needed.
as for the `build.sh`, it's possible to specify (w/ build) dependencies to speed up building, as I only use static library for arm, and currenly miniupnpc is not used (the version zerotier depends is too old). So improvements are appreciated ;)
=> addpkg(zerotier-one): 1.14.0

tur-hacking/zaproxy/build.sh, tur-hacking/zaproxy/zap.desktop
`zap.png` can be generated from `magick zap.ico[0] -resize 64x64 $PREFIX/share/pixmaps/zap.png`. 
It should be better to generated in build time, but installation of the `imagemagick` in the host ubuntu os seems to be a hassle.
=> addpkg(tur-hacking/zaproxy): 2.15.0

tur/rife-ncnn-vulkan-nihui/build.sh, tur/rife-ncnn-vulkan-tntwise/build.sh
=> rife-ncnn-vulkan-{tntwise,nihui}: bump and fix libomp.so error

.github/workflows/package_continuous.yml, .github/workflows/package_on_device.yml, .github/workflows/packages.yml
Basically adapted from https://github.com/termux/termux-packages/commit/0bff714afc6ce9351360984916146590d3376276
allow github build more conveniently thru pushing to `dev/*` or `dev` branch. 
may also revise readme.md accordingly.
=> github actions: allow runs on development branches

tur/ollama/build.sh
Go-based LLM runner, using cpu.  
Perhaps it would be good to have `ollama-vulkan` package when vulkan is implemented by ollama (WIP now) and no longer buggy for adreno in llama.cpp. 
Tested with
```
ollama serve
```
and then
```
ollama run phi3
```
=> new package: ollama

tur/ollama/build.sh
Should be built with openblas backend otherwise too slow and non-usable. 
```
ollama run --verbose phi3
```
the `--verbose` can provide the tokens/s stats after answered. 
FYI, my device (snapdragon 8G2) can generate tokens/s using `qwen2:1.5b` model using this package.
=> ollama: openblas backend

tur/tabby/0001-llama-cpp-crosscompiling.patch, tur/tabby/build.sh
Open-source AI coding assistant, a promising alternative to copilot. 
Command to test:
```
tabby serve --model DeepseekCoder-1.3B --chat-model Qwen2-1.5B-Instruct
```
Then go to localhost:8080 to register an account. May also try the VS Code plugin so it work like copilot. 
Same as ollama, OpenBLAS (cpu) backend is used and no GPU / NPU backend is currently available.
=> new package: tabby

tur/box2d/0001-aligned_alloc.patch, tur/box2d/0002-unsupported-cpu.patch, tur/box2d/build.sh, tur/cppunit/build.sh, tur/libabw/build.sh, tur/libcdr/build.sh, tur/libe-book/0001-TRUE-def.patch, tur/libe-book/build.sh, tur/libepubgen/build.sh, tur/libetonyek/build.sh, tur/libexttextcat/build.sh, tur/libixion/build.sh, tur/liblangtag/build.sh, tur/libmspub/build.sh, tur/libmwaw/build.sh, tur/libnumbertext/build.sh, tur/libodfgen/build.sh, tur/liborcus/build.sh, tur/libpagemaker/build.sh, tur/libpagemaker/libpagemaker-0.0.4-const-ref-exception.patch, tur/libqxp/build.sh, tur/libstaroffice/build.sh, tur/libvisio/build.sh, tur/libwpd/build.sh, tur/libwpg/build.sh, tur/libwps/build.sh, tur/libzmf/0001-long-uint-comparison.patch, tur/libzmf/build.sh, tur/mdds/build.sh, tur/redland/build.sh
=> libreoffice deps

tur-on-device/lpsolve/0001-timeb.h.patch, tur-on-device/lpsolve/build.sh, tur-on-device/lpsolve/lpsolve-5.5.2.11-misc.patch
part of #1180 but it seems that on device build should pulled separately.
=> new package: lpsolve

tur/python-pandas/build.sh
=> python-pandas: bump to 2.2.3

tur/clucene/0010-adapt-for-c++17-above.patch, tur/clucene/build.sh, tur/cppunit/build.sh
* clucene needs to be compile with clang c++20 during libreoffice build time, applying patch from gentoo
* cppunit needs `libcppunit.so` though there may be a better than `ln -sr $PREFIX/lib/libcppunit-1.15.so $PREFIX/lib/libcppunit.so`
=> libreoffice deps fix: clucene and cppunit

tur/python-pycryptodomex/build.sh
=> python-pycryptodomex: bump to 3.21.0

tur/pacman-contrib/build.sh
This came up in the Discord, specifically the systemd services not being removed.
So I decided to take a look at a build script and to be diplomatic this was just really damn sloppy.
I overhauled the build script and updated the package to the latest version.
<h1><em></em></h1> 
I don't want to keep banging on about this, but I just want to quickly point out how many problems the old build script had.
- Systemd services were not being removed
- `paclist` was getting shipped despite supposedly being disabled
because accessing an array without an index only returns the first element.
https://github.com/termux-user-repository/tur/blob/d83bcc0b428088a99b4be6d0cc6b5c9c7a46f2cd/tur/pacman-contrib/build.sh#L26-L28
- That entire removal shenanigans should have been put into …
=> bump(tur/pacman-contrib): 1.10.6

tur/rustc-nightly/build.sh
=> rustc-nightly: bump to 1.84.0-2024.10.14-nightly

tur/libnsl/build.sh
fix libnsl not registered
from issue #1267
=> libnsl: revbump to rebuild

README.md
Add a note with instructions to add the extra index URL to pip.conf.
Not really relevant to this PR, but I personally also have the pip cache set as well, since I update infrequently (*months* in between) and have many packages and frequently forget to flush the cache; this allows Android to manage that.
```
[global]
cache-dir = /data/data/com.termux/cache/pip
```
=> Add PyPI extra index URL to pip.conf

tur/luanti/build.sh, tur/luanti/minetest-bionic-libc-x11-wsi-opengl-es-2.patch, tur/luanti/minetest-fix-elf-directory-for-cross-compiling.patch
Fixes #1295 
Tested on Samsung Galaxy S9 SM-G960U with Qualcomm Adreno 630 GPU using these commands
```
termux-x11 &
DISPLAY=:0 LIBGL_ALWAYS_SOFTWARE=1 xfce4-session &
mkdir -p ~/.minetest/games/
git clone https://git.minetest.land/VoxeLibre/VoxeLibre.git ~/.minetest/games/VoxeLibre
DISPLAY=:0 LIBGL_ALWAYS_SOFTWARE=0 MESA_LOADER_DRIVER_OVERRIDE=zink MESA_VK_WSI_DEBUG=sw luanti
```
> [!TIP]
> For this type of game (X11 window system with fully functional builtin multitouch touchscreen buttons) I recommend trying out this mode of Termux:X11 while playing:
> ![image](https://github.com/user-attachments/assets/b699793a-3c9e-4679-8e7a-e22d44f05dc9)
=> addpkg(tur/luanti): minetest for X11 on Android

tur/luanti/build.sh
I had packaged the development branch in preparation for the release today on github
https://github.com/minetest/minetest/releases/tag/5.10.0
that has almost identical code, but is now a stable release
=> bump(tur/luanti): stable release 5.10.0 and turn on auto update

.github/workflows/package_continuous.yml, .github/workflows/packages.yml, big-pkgs.list, tur-continuous/electron/build.sh, tur/rustc-nightly/build.sh
- made minor changes to `electron` and `rustc-nightly` packages so they pass the check by `scripts/lint-packages.sh` (fixing https://github.com/termux-pacman/tur/issues/2 and https://github.com/termux-pacman/tur/issues/5)
- changed ubuntu version (from 22.04 to 24.04) in yml scripts
- added `big-pkgs.list` file for correct operation of mirror repository
I'll note that it's not just `electron` and `rustc-nightly` that have compilation issues. There are also issues with `supertuxkart`, `libandroid-mathlib`, `electron-headers-for-code-oss` and `dd_rescue` (though with the latter, it's probably a problem with the Termux-Pacman service algorithms). You can find all the information here - https://github.com/termux-pacman/tur/issues.
=> fixing some packages and improving yml scripts

tur/chromium/build.sh
Closes #1182 
Closes termux-user-repository/chromium-builder#33
=> chromium: revbump

tur/instfd/build.sh
It appears termux doesn't automatically handle python deps... Add postinst debscript manually.
=> instfd: add deb postinst

tur/code-oss/build.sh
=> code-oss: fix crash when generating shortcut text for super accelerator

tur/archisteamfarm/build.sh
Fix "ERROR: Another build is already running within same environment."
[no ci]
=> fix(tur/archisteamfarm): shutdown dotnet build server

tur/payload-dumper-go/0001-gozstd-fetch-source.patch, tur/payload-dumper-go/0002-gozstd-support-i686.patch, tur/payload-dumper-go/build.sh
This package only supports ARM and ARM64 and does not support other architectures.
=> addpkg(tur/payload-dumper-go): 1.3.0

tur-on-device/bazel5/0005-import-termux-patches.patch, tur-on-device/bazel5/build.sh, tur-on-device/bazel5/dep-patches/grpc-upb-clang-19.patch, tur-on-device/bazel5/dep-patches/grpc-upb-config.patch, tur-on-device/bazel5/dep-patches/grpc-upb.patch, tur-on-device/bazel5/dep-patches/upb-clang-19.patch, tur-on-device/bazel5/dep-patches/upb-config.patch
- Fixes #1580
- Cherry-pick https://github.com/protocolbuffers/protobuf/commit/21af7830ad5ff34798d7c5c8c70c30b450f6634e
- Add `-Wno-c11-extensions` in the necessary places to be compatible with the cherry-pick
=> fix(tur-on-device/bazel5): cherry-pick upb clang compatibility patch

tur-on-device/gnome-sudoku/build.sh
Bringing gnome games, but I have problem: 
https://github.com/user-attachments/assets/633026bb-048a-484b-af0e-0824e5bad400
I created discussion in termux/termux-packages repo about ["How I get fully native gpu?"](https://github.com/termux/termux-packages/discussions/23961) and nobody answered because I didn't write problem description that I had no idea to write.
Or maybe opengl's issue? It lack of GLX_EXT_swap_control or GLX_MESA_swap_control that I tested with glmark2.
=> New pkg: gnome-sudoku

tur/rustc-nightly/build.sh, tur/rustc-nightly/config.toml
=> rustc-nightly: bump to 1.88.0-2025.04.04-nightly

tur/apkeditor/build.sh, tur/apkeditor/wrapper.in
- Select APKEditor-*.jar, which can be downloaded from the latest build, with the highest version in `/libexec/apkeditor`. Which can be linked anywhere btw.
- Remove an unnecessary Java argument.
=> chore(tur/apkeditor): runnable latest jar

tur-on-device/python2-numpy/build.sh
- Fixes https://github.com/termux-user-repository/tur/issues/1781
=> fix(tur-on-device/python2-numpy): explicitly link to `libm.so`

tur-on-device/pixz/build.sh
- Fixes https://github.com/termux-user-repository/tur/issues/1779
=> fix(tur-on-device/pixz): use `autoreconf -fi` to build with `automake-1.17`

tur/smallerc/0001-make-stop-mangling-PATH.patch, tur/smallerc/build.sh
It was setting PATH in makefiles to just-built executables, failing the local build, as we need to use executables from smallerc-cross subpackage rather than the just-built ones.
Related: #1833
=> smallerc: fix PATH problems

tur/dosemu2/build.sh
It turned out dosemu2 was finding libx11 during build and was enabling the basic GUI support, even if I didn't ask it for that.
This patch enables the official GFX support via libsdl2. It disables outdated X support which currently needs libandroid-shmem and its not being linked in.
Related: #1833
=> dosemu2: add gfx support

tur/python-tokenizers/build.sh
=> python-tokenizers: bump to 0.22.1
