termux-user-repository/tur

.github/workflows/packages.yml
tur/sample-pkg-example/build.sh

Sample-pkg-example

---

repo.json

repo.json: add termux main repo

---

tur/libandroid-mathlib/LICENSE
tur/libandroid-mathlib/build.sh
tur/libandroid-mathlib/fpmath.h
tur/libandroid-mathlib/math_private.h
tur/libandroid-mathlib/s_clog.c
tur/libandroid-mathlib/s_clogf.c
tur/libandroid-mathlib/s_cpow.c
tur/libandroid-mathlib/s_cpowf.c
tur/libllvm-classic-flang/build.sh
tur/libllvm-classic-flang/clang-lib-Driver-ToolChain.cpp.patch
tur/libllvm-classic-flang/clang-lib-Driver-ToolChains-Gnu.cpp.patch
tur/libllvm-classic-flang/clang-lib-Driver-ToolChains-Linux.cpp.patch
tur/libllvm-classic-flang/llvm-tools-llvm-shilib-CMakeLists.txt.patch
tur/libllvm-classic-flang/openmp.patch

These packages are the dependencies of an on-device package `classic-flang`.

new package: libandroid-mathlib, libllvm-classic-flang

---

tur/ruby-2/Makefile.in.patch
tur/ruby-2/build.sh
tur/ruby-2/ext-etc-etc.c.patch
tur/ruby-2/ext-syslog-extconf.rb.patch
tur/ruby-2/fix-paths.patch
tur/ruby-2/lib-rubygems-install_update_options.rb.patch
tur/ruby-2/mkmf.rb.patch
tur/ruby-2/process.c.patch
tur/ruby-2/pty.c.patch
tur/ruby-2/ruby-is-ruby2.subpackage.sh
tur/ruby-2/ruby-ri-2.subpackage.sh
tur/ruby-2/tests/default_encoding_isutf8.sh
tur/ruby-2/tests/extension_modules_installed.sh
tur/ruby-2/tool-rbinstall.rb.patch

new package: ruby 2

---

tur/ardentryst/build.sh

If possible, please check on clean Termux that all dependencies are met. (Based on Debian's requirements - there are all the most important)
The game requires X11 Server.

New Package: Ardentryst

---

tur/dlib/build.sh

new package: dlib

---

tur/gtkcord4/build.sh

Re https://github.com/termux/termux-packages/pull/11938

new package : gtkcord4

---

tur/vomit/build.sh

what: in-developing `isync(1)`+mblaze slim analogue

vomit: new pkg

---

tur/dcfldd/build.sh

https://repology.org/project/dcfldd/versions

dcfldd: add new package

---

tur/zphisher/build.sh

SHASUM 256 : c2b167d7fea616792f6ad2fe970e804815e555d801ab8f2bb19c966ac9c1ca1c  2.3.2.tar.gz

[zphisher] latest release v2.3.2

---

tur/openalut/000_configure.diff
tur/openalut/001_freebsd_pthread.diff
tur/openalut/005_am_maintainer_mode.diff
tur/openalut/006_findutils_syntax.diff
tur/openalut/build.sh
tur/python-opengl/build.sh
tur/trigger-rally/build.sh
tur/trigger-rally/fix-sdl2-detection.patch
tur/trigger-rally/libtinyxml2-7.0.0.patch
tur/trigger-rally/patch.patch
tur/trigger-rally/verbose-build.patch

new pkgs: openalut , python-opengl, trigger

---

tur/vhs/build.sh

new package : vhs

---

tur/code-server/0001-patch-commit.patch.beforehostbuild
tur/code-server/0002-vscode-postinstall-no-git.patch.beforehostbuild
tur/code-server/0003-vscode-fix-pathes.patch.beforehostbuild
tur/code-server/build.sh

new package: code-server

---

tur/mongodb/0001-libcxx-android-no-deduction-guides-in-memory.patch
tur/mongodb/0002-revert-7f574fb632c18e96a4dc6df88c476b9b68da4980.patch
tur/mongodb/0003-add-dns_query_android-impl.h.patch
tur/mongodb/0004-add-stack_locator_android.cpp.patch
tur/mongodb/0005-add-processinfo_android.cpp.patch
tur/mongodb/0006-add-ftdc_system_stats_android.cpp.patch
tur/mongodb/0007-fix-hardcoded-pathes.patch
tur/mongodb/build.sh

new package: mongodb

---

tur/abuse/build.sh

new package: abuse

---

tur/abuse-frabs/build.sh

new package: frabs

---

tur/python-mitmproxy-wireguard/build.sh

new package: python-mitmproxy-wireguard

---

tur/php7/build-php.m4.patch
tur/php7/build.sh
tur/php7/ext-opcache-config.m4.patch
tur/php7/ext-opcache-zend_accelerator_module.c.patch
tur/php7/ext-pdo_pgsql-config.m4.patch
tur/php7/ext-pgsql-config.m4.patch
tur/php7/ext-phar-Makefile.frag.patch
tur/php7/ext-posix-posix.c.patch
tur/php7/ext-standard-basic_functions.c.patch
tur/php7/ext-standard-dns.c.patch
tur/php7/ext-standard-php_fopen_wrapper.c.patch
tur/php7/ext-standard-proc_open.c.patch
tur/php7/iconv-config.m4.patch
tur/php7/pear-Makefile.frag.patch
tur/php7/php-fpm.patch
tur/php7/php7-apache.subpackage.sh
tur/php7/php7-fpm.subpackage.sh
tur/php7/php7-pgsql.subpackage.sh
tur/php7/sapi-apache2handler-config.m4.patch
tur/php7/use-local-fastcgi-header.patch

new package: php7

---

tur/go-cqhttp/build.sh
tur/go-cqhttp/fix-upstream-android-build.patch

upgpkg(tur/go-cqhttp): v1.0.0-rc4

---

tur-hacking/zphisher/build.sh

Update to version 2.3.5

---

tur/mesa-zink/build.sh
tur/mesa-zink/cmake-wrapper.in
tur/mesa-zink/enable-system_has_kms_drm-for-android.patch
tur/mesa-zink/fix-for-x11.patch
tur/mesa-zink/mesa-zink-dev.subpackage.sh
tur/mesa-zink/meson.build.patch
tur/mesa-zink/osmesa-zink.subpackage.sh
tur/mesa-zink/src-gallium-drivers-llvmpipe-lp_screen.c.patch
tur/mesa-zink/vtest-socket-path.patch
tur/virglrenderer-mesa-zink/build.sh
tur/virglrenderer-mesa-zink/vtest-vtest_protocol.h.patch

These packages are tested on Adreno (TM) 660 and work fine.
Closes #271.
CC: @IntinteDAO

new package: mesa-zink

---

tur/vhs/build.sh
tur/vhs/fix_chromium_path.patch

bump(vhs): 0.2.0

---

tur-on-device/thc-hydra/0002-disable-fdsan.patch
tur-on-device/thc-hydra/build.sh

thc-hydra: disable fdsan

---

tur/rustc-nightly/build.sh

rustc-nightly: fix rpath

---

tur/python-kivy/build.sh

bump(tur/python-kivy): 2.2.0.dev0

---

tur/davegnukem/0001-add-appstream-metadata.patch
tur/davegnukem/0002-build-reproducibly.patch
tur/davegnukem/0003-build-on-big-endian-systems.patch
tur/davegnukem/0004-allow-flags-injection.patch
tur/davegnukem/build.sh

new package: davegnukem

---

tur/gcc-default/postinst.sh.in
tur/gcc-default/prerm.sh.in

Close #359
Question for @licy183: Are there any other packages in TUR that interact with dpkg in some way?

tur/gcc-default: fix postinst and prerm scripts

---

tur/code-server/build.sh

code-server: link against libandroid-spawn

---

tur-on-device/blender/build.sh

chore(tur-on-device/blender): stick to specific commit

---

tur/hare/Makefile.patch
tur/hare/build.sh
tur/hare/config.mk
tur/hare/cross_setup.sh
tur/hare/hare-cross.subpackage.sh
tur/hare/path.patch
tur/hare/syscalls.patch.beforehostbuild
tur/harec/build.patch
tur/harec/build.sh
tur/harec/cross_setup.sh
tur/harec/harec-cross.subpackage.sh
tur/qbe/Makefile.patch.beforehostbuild
tur/qbe/build.sh
tur/qbe/cross_setup.sh
tur/qbe/qbe-cross.subpackage.sh

This adds the Hare language packages.
This includes `harec` the bootstrap compiler and `hare` an overall toolset.
~~The build of `hare` on my android device varied a lot depending on the used compiler/linker/assembler.~~
~~I hope they run in the CI.~~
~~I will merge all commits to 2 commits later!~~
Edit: Done

[tur] new package hare

---

common-files/building-system-patches/0004-add-packages-in-setup-termux.patch
tur-on-device/python-pandas/build.sh

bump(tur/python-pandas): 2.0.1

---

common-files/building-system-patches/0004-add-packages-in-setup-termux.patch
tur-on-device/python-tokenizers/build.sh

new package: python-tokenizers

---

tur/dpp/0001-fix-ambiguous-user.patch
tur/dpp/build.sh

I'm adding this because this package is less popular 
D++ is a lightweight and efficient library for Discord written in modern C++, covering as much of the API specification as possible with an incredibly small memory footprint even when caching large amounts of data.

[New Package]: DPP

---

tur/lib-tls-client/build.sh
tur/python-tls-client/0001-fix-library-path.patch
tur/python-tls-client/build.sh

new package: lib-tls-client, python-tls-client

---

tur/python-pygame/build.sh

python-pygame: bump to 2.4.0

---

tur/arpack-ng/build.sh

update arpack-ng (for update octave)

update arpack-ng to 3.9.0

---

tur/smartdns/0001-add-getdomainname-for-android.patch
tur/smartdns/0002-fix-hardcoded-pathes.patch
tur/smartdns/0003-do-not-call-setuid.patch
tur/smartdns/0004-do-not-install-systemd-related-files.patch
tur/smartdns/0005-fix-int-types.patch
tur/smartdns/build.sh

new package: smartdns

---

tur/nodejs-12/avoid-ficlone-ioctl.patch
tur/nodejs-12/backport-v8-00604cd2806b5d26bef592dd19989a234bd07a4b.patch
tur/nodejs-12/build.sh
tur/nodejs-12/configure.py.patch
tur/nodejs-12/deps-uv-src-unix-core.c.patch
tur/nodejs-12/deps-uv-uv.gyp.patch
tur/nodejs-12/deps-v8-src-flags-flag-definitions.h.patch
tur/nodejs-12/deps-v8-src-logging-log.cc.patch
tur/nodejs-12/fix_multiple_definitions.patch
tur/nodejs-12/lib-child_process.js.patch
tur/nodejs-12/lib-os.js.patch
tur/nodejs-12/node.gyp.patch
tur/nodejs-12/npm-link-patch.patch
tur/nodejs-12/src-cares_wrap.cc.patch
tur/nodejs-12/src-node_internals.h.patch
tur/nodejs-12/src-node_main.cc.patch
tur/nodejs-12/tools-v8_gypfiles-v8.gyp.patch
tur/nodejs-12/v8-call-new-ListFormatter-createInstance.patch

new package: nodejs-12

---

tur/code-oss/build.sh

code-oss: bump to 1.79.0

---

tur-on-device/python-pywavelets/build.sh
tur-on-device/python-scikit-image/build.sh

new package: python-{pywavelets,scikit-image}

---

tur-hacking/aircrack-ng/build.sh
tur-hacking/mdk4/build.sh
tur-hacking/mdk4/src-attacks-poc.c.patch
tur-hacking/mdk4/src-channelhopper.c.patch

add(tur-hacking): aircrack-ng,mdk4

---

tur/xpenguins/build.sh

Not sure if we need it, but why not :)

new package: xpenguins

---

tur/libftgl2/0001-upstream-bf07517ded4704be37eef39b758b5206fc6f4f0d.patch
tur/libftgl2/0002-upstream-835f2ba7911a6c15a1a314d5e3267fa089b5a319.patch
tur/libftgl2/0003-upstream-778b8f21ba0b71289aef37e3422d008456445971.patch
tur/libftgl2/0004-upstream-8763fa4e413e015e46376697fb8ab59ed31c2ff5.patch
tur/libftgl2/0005-upstream-a867c7a2e02ab8b47b1322f2903cfaa44c756b9b.patch
tur/libftgl2/0006-no-eps.patch
tur/libftgl2/build.sh

new package: libftgl2

---

tur/libllvm-14/build.sh
tur/libllvm-14/llvm-14.subpackage.sh
tur/libllvm-14/llvm-include-llvm-ADT-SmallVector.h.patch
tur/libllvm-14/llvm-tools-llvm-rtdyld-llvm-rtdyld.cpp.patch
tur/libllvm-14/llvm-tools-llvm-shlib-CMakeLists.txt.patch

new package: libllvm-14

---

tur-on-device/blender/build.sh

Closes #487 
Really sorry for late.

tur-on-device(blender): bump to latest commit

---

tur/python-scipy/build.sh

python-scipy: bump to 1.11.2

---

tur/python-scipy/build.sh

python-scipy: fix build

---

tur/hurrican/0001-do-not-include-timeb.h.patch
tur/hurrican/build.sh

new package: hurrican

---

tur/aptitude/aptitude.patch
tur/aptitude/build.sh
tur/aptitude/fix-FTBFS-1011681.patch
tur/aptitude/fix-hardcoded-paths.patch
tur/aptitude/rpmatch.patch
tur/aptitude/src-Makefile.am.patch
tur/libcwidget/build.sh
tur/libcwidget/pthread_cancel.patch

new package: aptitude

---

tur/python-pandas/build.sh

python-pandas: bump to 2.1.0

---

tur-hacking/nbtscan/build.sh

new package: nbtscan

---

tur/python-brotli/build.sh
tur/python-brotli/wrapper.py.in
tur/python-pycryptodomex/build.sh
tur/python-yt-dlp/build.sh

new package: python-yt-dlp

---

tur-on-device/python2-numpy/build.sh
tur-on-device/python2-numpy/site.cfg.patch

new package: python2-numpy

---

tur/efte/0001-use-host-build-bin2c.patch
tur/efte/build.sh

new package: efte

---

tur-on-device/python2-scipy/build.sh
tur-on-device/python2-scipy/wrapper.in

new package: python2-scipy

---

tur/moarvm/0001-no-pthread_yield.patch
tur/moarvm/build.sh

new package: moarvm

---

tur-on-device/nqp/build.sh

new package: nqp

---

tur/exatorrent/build.sh
tur/exatorrent/fix-hardcoded-etc-resolv-conf.diff
tur/exatorrent/fix-hardcoded-etc-resolv-conf.sh

new package: exatorrent

---

tur/ddns-go/build.sh

new package: ddns-go

---

tur/ddclient/0001-fix-hardcoded-pathes.patch
tur/ddclient/build.sh

new package: ddclient

---

tur/iamb/0001-arboard-dummy-platform.diff
tur/iamb/build.sh

new package: iamb

---

tur/python-pygame/build.sh

python-pygame: bump to 2.5.2

---

tur/meli/0001-disable-dbus.patch
tur/meli/build.sh

new package: meli

---

tur/hurl/build.sh

hurl: bump to 4.1.0

---

tur-on-device/python-scikit-image/build.sh

python-scikit-image: bump to 0.22.0

---

tur/code-oss/0001-use-custom-native-keymap.patch
tur/code-oss/build.sh

code-oss: bump to 1.82.0

---

tur-on-device/perl-net-ssleay/build.sh

~~Also done to rebuild after perl upgrade.~~ Just kidding, perl was not upgraded recently

bump(tur-on-device/perl-net-ssleay): update to 1.93_02

---

tur/openspecfun/build.sh

new package: openspecfun

---

tur-on-device/python-pywavelets/build.sh

python-pywavelets: bump to 1.5.0

---

tur/aptitude/aptitude.patch
tur/aptitude/build.sh

aptitude: revbump to rebuild with boost 1.83

---

tur/code-oss/build.sh

See https://github.com/termux-user-repository/tur/issues/732

code-oss: revbump to rebuild

---

tur-multilib/hangover-wine/0001-fix-paths.patch
tur-multilib/hangover-wine/0002-fix-defines.patch
tur-multilib/hangover-wine/0003-fix-socket-ipx.patch
tur-multilib/hangover-wine/0004-fexcore-incompatible-function-pointer-types.patch
tur-multilib/hangover-wine/0005-deprecate-opt-library-location.patch
tur-multilib/hangover-wine/9997-fix-winebuild-as-type.patch.beforehostbuild
tur-multilib/hangover-wine/9998-fix-winegcc-build-target.patch.beforehostbuild
tur-multilib/hangover-wine/9999-fix-winegcc-flags-for-arm.patch.beforehostbuild
tur-multilib/hangover-wine/build.sh

Tested with a simple Hello World program.
```
~ $ wine aarch64-test.exe 
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0050:err:systray:initialize_systray Could not create tray window
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
005c:err:dnsapi:DllMain No libresolv support, expect problems
Hello World
```
```
~ $ wine i686-test.exe 
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0050:err:winediag:nodrv_CreateWindow Application tried to …
```

new package: hangover-wine

---

tur-on-device/blender/build.sh
tur-on-device/blender/no-error-float_conversion-double_promotion.patch

tur-on-device(blender): update to latest commit

---

tur/surreal/build.sh
tur/surreal/jemalloc-sys.diff

surreal: bump to 1.1.0

---

tur/dadadodo/build.sh

new package: dadadodo

---

tur/64tass/0001-memalign-conflict.patch
tur/64tass/build.sh

new package: 64tass

---

tur/python-pandas/build.sh

python-pandas: bump to 2.2.0

---

tur/bfm/build.sh

https://github.com/termux/termux-packages/issues/19051

addpkg(tur/bfm): ez file manager slokes in bash

---

tur/playit/build.sh

First time contributing on this repo, feel free to comment or change anything wrong

New package: playit

---

tur/stern/build.sh

feel free to let me know or change anything if there are any mistakes

new package: stern

---

tur/python-polars/build.sh
tur/python-polars/cmake-0.1.50-src-lib.rs.diff
tur/python-polars/jemalloc-sys-0.5.4+5.3.0-patched-src-lib.rs.diff

new package: python-polars

---

tur/smartdns/0001-add-getdomainname-for-android.patch
tur/smartdns/0002-fix-hardcoded-pathes.patch
tur/smartdns/0005-avoid-pthread_cancel.patch
tur/smartdns/build.sh

smartdns: bump to 45

---

tur/xfdashboard/build.sh

new package: xfdashboard

---

tur-on-device/perl-net-ssleay/build.sh

perl-net-ssleay: revbump to rebuild

---

tur-multilib/winetricks/build.sh

This `termux_pkg_auto_update()` is largely based on the [build.sh of clvk package](https://github.com/termux/termux-packages/blob/master/packages/clvk/build.sh) from the main repo termux/termux-packages.

new package: winetricks

---

tur/libiptcdata/build.sh

One of dependencies of rawtherapee

new package: libiptcdata

---

tur/libiptcdata/build.sh
tur/rawtherapee/0001-dirbrowser-root-subdirs.patch
tur/rawtherapee/build.sh

Tested on my aarch64 device and works for several sample DNG files. Not tested on other architectures.

new package: rawtherapee

---

tur/python-scipy/0001-pr-19909.patch
tur/python-scipy/build.sh

python-scipy: bump to 1.12.0

---

tur/cfitsio/0001-cmake-libm.patch
tur/cfitsio/build.sh
tur/wcslib/0001-remove-AC_CHECK_FILE.patch
tur/wcslib/0002-skip-makefile-configure.patch
tur/wcslib/build.sh

They are dependencies of astrometry.net (https://astrometry.net/doc/build.html) which I am working on to build a package.

new packages: wcslib and cfitsio

---

tur/python-polars/build.sh

python-polars: bump to 0.20.11

---

common-files/build-termux-docker.sh

- Breaks [common-files/build-termux-docker.sh](https://github.com/termux-user-repository/tur/blob/57b28c4921381567294b456370e2b4818e5d2512/common-files/build-termux-docker.sh) unless termux-user-repository/termux-docker#1 is merged

Call entrypoint on docker-exec

---

common-files/building-system-patches/0003-add-packages-in-setup-termux.patch

- termux-user-repository/termux-docker#1

remove update-static-dns from build system patch

---

tur/dillo/0001-Use-memset-instead-of-bzero.patch
tur/dillo/0002-fix-OpenSSL-1.1-detection.patch
tur/dillo/build.sh

From https://github.com/termux/termux-packages/pull/19411

addpkg(tur/dillo): 3.0.5

---

tur/python-yt-dlp/build.sh

bump(tur/python-yt-dlp): 2024.03.10

---

tur-multilib/wine-devel/0001-fix-paths.patch
tur-multilib/wine-devel/0002-fix-defines.patch
tur-multilib/wine-devel/0003-fix-socket-ipx.patch
tur-multilib/wine-devel/0004-no-pthread_mutexattr_setprotocol.patch
tur-multilib/wine-devel/9998-fix-winegcc-build-target.patch.beforehostbuild
tur-multilib/wine-devel/9999-fix-winebuild-as-type.patch.beforehostbuild
tur-multilib/wine-devel/build.sh

new package: wine-devel

---

tur/iamb/build.sh

iamb: bump to 0.0.9

---

tur/tmux-sixel/build.sh
tur/tmux-sixel/compat-imsg.c.patch
tur/tmux-sixel/compat-setproctitle.c.patch
tur/tmux-sixel/compat.h.patch
tur/tmux-sixel/configure.ac.patch
tur/tmux-sixel/tmux.conf
tur/tmux-sixel/tmux.h.patch

new package: tmux-sixel

---

tur/surreal/build.sh

surreal: bump to 1.4.0

---

tur/ffplayout/0001-fix-hardcoded-paths.patch
tur/ffplayout/build.sh

ffplayout: bump to 0.21.1

---

tur/bitmagnet/build.sh

bitmagnet: bump to 0.7.14

---

tur/nodejs-18/build.sh

nodejs-18: use bundled libicu

---

tur/libdicom/build.sh
tur/openslide/build.sh

new package: openslide

---

tur/browsh/build.sh

new package: browsh

---

tur/python-polars/arboard-dummy-platform.diff
tur/python-polars/build.sh

python-polars: bump to 0.20.24

---

tur/meli/0001-disable-dbus.patch
tur/meli/0002-use-system-libsqlite.patch
tur/meli/build.sh

meli: bump to 0.8.5

---

tur/chromium/build.sh

chromium: enable auto-update

---

tur/dotload/build.sh

I added my `dotload` package to your repository, here is the package page - https://github.com/okineadev/dotload
I have one question - is it possible to auto-update the package?
I would like to automatically update my package in this repository when I create a new release

new package: dotload

---

tur/chromium/build.sh

chromium: bump to 124.0.6367.155

---

tur/openspecfun/0001-gfortran.patch
tur/openspecfun/build.sh

openspecfun: bump to 0.5.7

---

tur/chromium/build.sh

chromium: bump to 124.0.6367.207

---

tur/rawtherapee/0002-libjpeg-turbo-3.0.3.patch
tur/rawtherapee/build.sh

rawtherapee: link against libjpeg-turbo 3.0.3

---

tur/chromium/build.sh

chromium: bump to 125.0.6422.76

---

common-files/prebuilt-gcc.json
common-files/setup_toolchain_gcc.sh
tur/gcc-14/0001-android-related-modifications.patch
tur/gcc-14/0002-fix-missing-_L.patch
tur/gcc-14/0003-disable-call-ssp-local.patch
tur/gcc-14/0004-avoid-hard-link-install.patch
tur/gcc-14/0005-check-both-android-and-bionic-macro.patch
tur/gcc-14/0006-remove-sys-sysctl.h.patch
tur/gcc-14/0007-override-CXXFLAGS-in-Makefile.patch
tur/gcc-14/0008-explicitly-some-headers.patch
tur/gcc-14/build.sh
tur/gcc-14/specs.in
tur/gcc-default/build.sh
tur/gcc-default/gcc-default-10.subpackage.sh
tur/gcc-default/gcc-default-11.subpackage.sh
tur/gcc-default/gcc-default-13.subpackage.sh
tur/gcc-default/gcc-default-14.subpackage.sh
tur/gcc-default/gcc-default-9.subpackage.sh

new package: gcc-14

---

tur/libllvm-16/build.sh

libllvm-16: revbump to rebuild

---

tur/chromium/build.sh

chromium: bump to 125.0.6422.112

---

tur/chromium/build.sh

chromium: bump to 125.0.6422.141

---

tur/code-oss/build.sh

code-oss: bump to 1.90.0

---

tur/darktable/build.sh

- termux/termux-packages#20438

chore(tur/darktable): rebuild against `libicu` 75.1

---

tur-multilib/wine-devel/build.sh

wine-devel: enable WoW64 support for x64

---

tur/python-scipy/build.sh

See termux/termux-packages#20451

python-scipy: revbump to rebuild

---

tur/python-scipy/build.sh

python-scipy: bump to 1.14.0

---

tur/python-pygame/build.sh

bump(tur/python-pygame): 2.6.0

---

tur-hacking/bettercap/build.sh

Close #1122
https://github.com/1q23lyc45/tur/actions/runs/10330330061 This is the compiled output of CI.

addpkg(tur-hacking/bettercap): v2.33.0

---

tur-hacking/burpsuite-pro/LICENSE
tur-hacking/burpsuite-pro/build.sh
tur-hacking/burpsuite-pro/burpsuite-pro.desktop
tur-hacking/burpsuite/LICENSE
tur-hacking/burpsuite/build.sh
tur-hacking/burpsuite/burpsuite.desktop

Version higher than 2023.12.1.5 may require openjdk >= 21. 
LICENSE is from 
* https://portswigger.net/burp/eula/community
* https://portswigger.net/burp/eula/pro

addpkg(tur-hacking/burpsuite{,-pro}): 2023.12.1.5

---

tur/meli/build.sh

meli: bump to 0.8.6

---

tur/go-moreutils/0001-use-go-flags-from-env.patch
tur/go-moreutils/build.sh

new package: go-moreutils

---

tur/libcmis/0001-libxml2-2.12.patch
tur/libcmis/build.sh

new package: libcmis

---

tur/clucene/0001-clucene-core-2.3.3.4-install_contribs_lib.patch
tur/clucene/0002-clucene-core-2.3.3.4-pkgconfig.patch
tur/clucene/0003-fix_zlib_detections.patch
tur/clucene/0004-Fix-missing-include-time.h.patch
tur/clucene/0005-clucene-multimap-put.patch
tur/clucene/0006-clucene-narrowing-conversions.patch
tur/clucene/0007-clucene-debug.patch
tur/clucene/0008-do-not-use-try-run.patch
tur/clucene/0009-pthread_t.patch
tur/clucene/build.sh

new package: clucene

---

tur/libfreehand/build.sh
tur/libfreehand/libfreehand-0.1.2-icu-fix.patch
tur/librevenge/build.sh

new package: librevenge,libfreehand

---

tur/codon/build.sh
tur/codon/host-peg2cpp-CMakeLists.txt

codon: bump to 0.17.0

---

tur/openssl-1.1/Configurations-15-android.conf.patch
tur/openssl-1.1/apps-ocsp.c.patch
tur/openssl-1.1/build.sh
tur/openssl-1.1/e_os.h.patch
tur/openssl-1.1/openssl1.1-tool.subpackage.sh

Fix github actions dependency check error incurred by https://github.com/termux/termux-packages/commit/2188e154d5ebaa5e0d5aecb3059c81972ab8c316

moved from termux-packages: openssl-1.1

---

tur/mdds/build.sh

mdds: fix auto-update

---

tur/sdlpal/build.sh

new package: sdlpal

---

tur/clucene/build.sh

missed in previous commit and needed for libreoffice. thanks!

clucene: include contribs-lib

---

tur/surreal/build.sh
tur/surreal/librocksdb-sys.diff

surreal: bump to 2.0.3

---

tur-on-device/blender/build.sh

blender: revbump to rebuild

---

tur/rustc-nightly/build.sh

rustc-nightly: bump to 1.83.0-2024.10.11-nightly

---

tur-hacking/dsniff/build.sh

dsniff: revbump to rebuild

---

tur/ollama/0001-cgo-flags.patch
tur/ollama/build.sh

ollama: bump to 0.4.0

---

tur/ffplayout/0001-fix-hardcoded-paths.patch
tur/ffplayout/0002-use-pre-generated-html.patch
tur/ffplayout/build.sh

ffplayout: bump to 0.24.1

---

tur/rustc-nightly/0004-set-TMPDIR.patch
tur/rustc-nightly/build.sh
tur/rustc-nightly/rust-nightly-std-wasm32-wasi.subpackage.sh

rustc-nightly: bump to 1.85.0-2024.11.25-nightly

---

tur/code-server/build.sh

code-server: bump to 4.90.2

---

tur/code-oss/0005-use-open-vsx.org-as-extensions-gallery.patch
tur/code-oss/build.sh

code-oss: bump to 1.90.1

---

tur/rustc-nightly/build.sh
tur/rustc-nightly/config.toml

rustc-nightly: bump to 1.85.0-2024.12.06-nightly

---

tur/ffplayout/build.sh

See 35dc60ae1e9fb5e4cd9d2843411f6ef199f17659

ffplayout: fix build

---

tur/surreal/build.sh

surreal: bump to 2.1.3

---

tur/ollama/0001-cgo-flags.patch
tur/ollama/build.sh

ollama: bump to 0.5.2

---

tur-on-device/blender/0004-ffmpeg-7-channels.patch
tur-on-device/blender/0005-ffmpeg-7-duration.patch
tur-on-device/blender/0006-ffmpeg-7-read_seek.patch
tur-on-device/blender/build.sh

blender: link against ffmpeg 7

---

tur/hangover-wine/0001-fix-paths.patch
tur/hangover-wine/build.sh

hangover-wine: bump to 10.0~rc2

---

tur-multilib/wine-staging/0001-fix-paths.patch
tur-multilib/wine-staging/build.sh

wine-staging: bump to 10.0~rc2

---

tur/dosemu2/build.sh

dosemu2: add missing dep on instfd

---

tur/ddclient/0001-fix-hardcoded-pathes.patch
tur/ddclient/build.sh

ddclient: bump to 4.0.0

---

tur/hangover-wine/build.sh

Works on Termux without any problems

hangover-wine: bump to 10.0

---

tur/openimageio/build.sh

openimageio: link against opencv 4.2

---

tur/biome/build.sh

Biome is a formatter and linter tool for web development. However, since it is built with Rust, the compilation process is quite time-consuming (especially on older devices)
https://github.com/biomejs/biome

new package: biome

---

tur/filebrowser/build.sh

filebrowser: bump to 2.32.0

---

tur/codesnap/arboard-dummy-platform.diff
tur/codesnap/build.sh

new package: codesnap

---

tur/archisteamfarm/build.sh
tur/archisteamfarm/cc.sh.patch

Close termux/termux-packages#6144

addpkg(tur): archisteamfarm

---

tur/doukutsu-rs/0001-no-jni.patch
tur/doukutsu-rs/0002-use-system-sdl2.patch
tur/doukutsu-rs/9998-cpal-no-jni.diff
tur/doukutsu-rs/9999-webbrowser-no-jni.diff
tur/doukutsu-rs/build.sh

new package: doukutsu-rs

---

tur/code-server/build.sh

code-server: bump to 4.97.2

---

tur-multilib/wine-devel/0002-fix-defines.patch
tur-multilib/wine-devel/build.sh

wine-devel: bump to 10.2

---

tur-multilib/wine-staging/0002-fix-defines.patch
tur-multilib/wine-staging/build.sh

wine-staging: bump to 10.2

---

tur-on-device/bazel/0005-import-termux-patches.patch
tur-on-device/bazel/0007-disable-module_maps.patch
tur-on-device/bazel/build.sh

bump(tur-on-device/bazel): 7.5.0

---

tur/tabby/0001-llama-cpp-crosscompiling.patch
tur/tabby/build.sh

tabby: fix conflict

---

tur/python-tokenizers/build.sh

python-tokenizers: bump to 0.21.0

---

tur/nodejs-20/build.sh

See https://www.reddit.com/r/termux/comments/1jgb7zm

nodejs-20: fix conflict field

---

tur/rustc-nightly/build.sh
tur/rustc-nightly/config.toml

rustc-nightly: bump to 1.87.0-2025.03.20-nightly

---

tur/rustc-nightly/build.sh
tur/rustc-nightly/config.toml
tur/rustc-nightly/rustc-cranelift-codegen-aarch64-linux-android.subpackage.sh
tur/rustc-nightly/rustc-cranelift-codegen-x86-64-linux-android.subpackage.sh

rustc-nightly: enable cranelift codegen

---

tur-multilib/wine-devel/9998-fix-winegcc-build-target.patch.beforehostbuild
tur-multilib/wine-devel/build.sh

wine-devel: bump to 10.4

---

tur/libllvm-classic-flang/build.sh

libllvm-classic-flang: fix conflict

---

tur/rustc-nightly/build.sh
tur/rustc-nightly/config.toml

rustc-nightly: bump to 1.88.0-2025.04.07-nightly

---

tur/php7/build.sh

php7: revbump to rebuild

---

tur-hacking/openbullet2/build.sh

* Close termux/termux-packages#9797
Likely there's some features that are broken, but I can't test everything. Others can take over maintaining and patching.

addpkg(tur-hacking): openbullet2

---

tur/depotdownloader/0001-fix-perm-on-old-android.patch
tur/depotdownloader/build.sh

I forked TUR repo's archisteamfarm's build script to build DepotDownloader.

New package: DepotDownloader

---

tur/depotdownloader/build.sh

To be more clear about DepotDownloader package.
(taken description from DepotDownloader's official winget manifest.)

depotdownloader/build.sh: Change description.

---

tur-on-device/r-base/build.sh

r-base: enable readline

---

tur/lib-tls-client/0001-bump-internal-version.patch
tur/lib-tls-client/build.sh

lib-tls-client: bump to 1.9.1

---

tur/uutils-coreutils/0001-selinux.patch
tur/uutils-coreutils/build.sh

uutils-coreutils: bump to 0.1.0

---

tur/topiary/build.sh

addpkg(tur/topiary): 0.6.1

---

tur/filebrowser/0001-bolt-missing-maxMapSize.patch
tur/filebrowser/build.sh

filebrowser: bump to 2.32.1

---

tur/darktable/0003-openmp.patch
tur/darktable/build.sh

darktable: bump to 5.2.0

---

tur/libjemalloc/0001-sys-nothrow.patch
tur/libjemalloc/0002-fix-hardcoded-paths.patch
tur/libjemalloc/build.sh

new package: libjemalloc

---

tur/nodejs-22/build.sh
tur/nodejs-22/deps-uv-uv.gyp.patch

nodejs-22: remove `CONFLICTS` field

---

tur/wine-devel/0004-no-pthread_mutexattr_setprotocol.patch
tur/wine-devel/build.sh

wine-devel: bump to 10.15

---

tur/wine-staging/0004-no-pthread_mutexattr_setprotocol.patch
tur/wine-staging/build.sh

wine-staging: bump to 10.15

---

tur/zerotier-one/0001-mask-setattr.patch
tur/zerotier-one/0006-dummy-pthread-affinity.patch
tur/zerotier-one/0008-makefile-install-add-selftest.patch
tur/zerotier-one/build.sh

zerotier-one: bump to 1.16.0

---

tur/python-scipy/build.sh

python-scipy: bump to 1.16.2

---

tur/uutils-coreutils/build.sh

uutils-coreutils: bump to 0.2.2

---

tur/python-scipy/build.sh
tur/python-scipy/libunwind-extra.cpp

python-scipy: add stub for `__cxa_call_terminate`

---

tur/dosemu2/build.sh

I added only build-deps. Which seems not enough.

dosemu2: dep on sdl3 (#1833)
